name: dj-gan
channels:
- conda-forge
dependencies:
- python=3.7
- numpy
- scipy
- matplotlib
- pandas
- seaborn
- jupyter
- ipywidgets
- nbdime
- jupyter_nbextensions_configurator
- scikit-learn
- pytorch
- pip
- pip:
  - tensorflow
  - pip-tools
  - hub
  - hub[audio]

